config/routes.rb
Rails.application.routes.draw do
  root 'boards#new'
  resources :boards, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  attr_accessor :width, :height, :mines_count

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true, length: { maximum: 100 }

  serialize :cells, Array

  scope :search_by_name, -> (query) { where('name LIKE ?', "%#{ query }%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :validate_mines, only: :create

  def index
    @boards = params[:search] ? Board.search_by_name(params[:search]) : Board.order(created_at: :desc)
    page_number = params[:page].to_i.positive? ? params[:page] : 1
    @boards = @boards.page(page_number).per(5)
  end

  def new
    @board = Board.new
    @recent_boards = Board.order(created_at: :desc).limit(10)
  end

  def create
    @board = Board.new(email: board_params[:email], name: board_params[:name])
    @board.cells = MinesweeperBoard.generate_board(board_params[:width].to_i, board_params[:height].to_i, board_params[:mines_count].to_i)

    if @board.save
      redirect_to board_path(@board)
    else
      render :new
    end
  end

  def show
    @board = Board.find_by_id(params[:id])
  end

  private

  def board_params
    params.require(:board).permit(:name, :email, :width, :height, :mines_count)
  end

  def validate_mines
    if board_params[:mines_count].to_i > board_params[:height].to_i * board_params[:width].to_i
      flash[:alert] = 'Number of Mines can not be greater than the size of board.'
      redirect_back(fallback_location: root_path)
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board_errors.html.erb
<%  @board.errors.messages.each do |message| %>
  <li class="mines-error"> 
    <%= "#{message[0]} #{message[1][0]}" %>
  </li>
<% end %>

app/views/boards/_recent_boards.html.erb
<div class="recent-boards-list">
  <% recent_boards.each do |board| %>
    <div class="card recent-board">
      <div class="card-body">
        <h5 class="card-title"><%= link_to board.name, board_path(board) %></h5>
        <p class="card-text">
          <strong>Creator Email:</strong> <%= board.email %><br>
          <strong>Creation at:</strong> <%= board.created_at.strftime('%b %e, %Y %l:%M %p') %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/index.html.erb
<h2 class="card-title text-center all-board-heading">All Minesweeper Boards</h2>
<%= form_tag(boards_path, method: :get, class: 'form-inline mb-3') do %>
  <div class="input-group", id="search-bar">
    <%= text_field_tag(:search, params[:search], class: 'form-control', placeholder: 'Search boards by name') %>
    <div class="input-group-append search-btn">
      <%= submit_tag('Search', class: 'btn btn-outline-primary') %>
    </div>
  </div>
<% end %>
<table class="table table-striped index-board">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Board Name</th>
      <th scope="col">Creator Email</th>
      <th scope="col">Creation Date</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each_with_index do |board, index| %>
      <tr>
        <th scope="row"><%= index + 1 %> </th>
        <td><%= link_to board.name, board_path(board) %></td>
        <td><%= board.email %></td>
        <td><%= board.created_at.strftime('%b %e, %Y %l:%M %p') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div><%= paginate @boards %></div>

app/views/boards/new.html.erb
<p class="h1 gen-board">Generate Minesweeper Board</p>
<% if flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<div class="center">
  <% if @board.errors.any? %>
    <%= render partial: 'board_errors' %>
  <% end %>
  <%= form_for @board, url: boards_path, data: { parsley_validate: true } do |form| %>
    <div class="form-group">
      <%= form.label :email, 'Email address:', class: "form-label font-weight-bold" %>
      <%= form.email_field :email, class: "form-control", required: true, data: { parsley_type: "email" } %>
    </div>

    <div class="form-group">
      <%= form.label :width, 'Board Width:', class: "form-label font-weight-bold" %>
      <%= form.number_field :width, class: "form-control width", required: true, data: { parsley_type: "integer" }, min: 0 %>
    </div>

    <div class="form-group">
      <%= form.label :height, 'Board Height:', class: "form-label font-weight-bold" %>
      <%= form.number_field :height, class: "form-control height", required: true, data: { parsley_type: "integer" }, min: 0 %>
    </div>

    <div class="form-group">
      <%= form.label :mines_count, 'Number of Mines:', class: "form-label font-weight-bold" %>
      <%= form.number_field :mines_count, class: "form-control mines", required: true, data: { parsley_type: "integer" }, min: 0 %>
      <p class="hidden mines-error"> Number of mines can't be greater than the size of board.</p>
      <p class="hidden mines-disable"> Please fill height and width first in order to add mines.</p>
    </div>

    <div class="form-group">
      <%= form.label :name, 'Board Name:', class: "form-label font-weight-bold" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>
    
    <% unless @board.errors.any? %>
      <%= form.submit 'Generate Board', class: "btn btn-info general-btn submit-btn" %>
    <% end %>
    <% if @board.errors.any? %>
        <%= link_to 'Back', root_path, class: 'btn btn-info general-btn' %>
    <% end %>
  <% end %>
</div>


<% unless @board.errors.any?%>
  <h2 class="card-title text-center recent-board-heading">Recent Minesweeper Boards</h2>
  <% if @recent_boards&.any? %>
    <%= render partial: 'recent_boards', locals: { recent_boards: @recent_boards } %>
    <div class="view_all_boards" ><%= link_to "View All Generated Boards", boards_path %></div>
  <% else %>
    <div class="no-boards"> No boards have been generated yet. </div>
  <% end %>
<% end %>

app/views/boards/show.html.erb
<div class="container">
  <% if @board.present? %>
    <h1 class="mb-4 board-details">Board Details</h1>

    <div class="card bg-light mb-4">
      <div class="card-body">
        <span class="card-title">Board Name:</span>
        <span> <%= @board.name %> </span>
        </br>
        <span class="card-title">Creator Email:</span>
        <span> <%= @board.email %> </span>
      </div>
    </div>
    <div class="board-container">
      <div class="minesweeper-board">
        <% @board.cells.each do |row| %>
          <div class="board-row">
            <% row.each do |cell| %>
              <div class="board-cell">
                <%= cell == :x ? '💣' : '◻️' %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <p>Board not found.</p>
  <% end %>

  <%= link_to 'Back', root_path, class: 'btn btn-info general-btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'boards.css.scss', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/parsleyjs@2.10.2/dist/parsley.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>